### ISSUE TITLE
Complete Wireframe of Homepage

### ISSUE THREAD

**Issue by dannyb-421** [UB-CSE/course-project-a6-jallenlooksgoodinshorts#31]
Create wireframes for the homepage and the post page

Task tests:
1. Wireframe for the homepage was created using Figma

**Comment by jefitzpa** [comment]
Wireframe for homepage and posts:
https://www.figma.com/file/VKdfz3YgR8XahhqDcgjF5x/Homepage?node-id=0%3A1
