### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by dannyb-421** [UB-CSE/course-project-a6-jallenlooksgoodinshorts#69]
As a user i want to ensure that there are security precautions in place on the website so that i have a secure and seamless experience

Acceptance test:
Ensure that the user's password is securely stored on the database and is not stored in plaintext
Verify that there is no influence from an outside source while the user is on the site

**Comment by xandercovert** [comment]
Change all db functions from:
`from db import <functions>`
to import db

and modify all function calls to be db.<function>
